#!/usr/bin/env bash
# Write autopilot-local/.env.local from repo keys.env + .env (no secrets printed).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/autopilot-local/.env.local"

get() {
  local key="$1"
  grep -E "^${key}=" "$ROOT/keys.env" 2>/dev/null | tail -1 | cut -d= -f2- || true
}

alpaca_key="$(get APCA_API_KEY_ID)"
alpaca_secret="$(get APCA_API_SECRET_KEY)"
alpaca_url="$(get APCA_ENDPOINT)"
sec_key="$(get SEC_API_KEY)"
quiver_key="$(grep -E '^QUIVER_API_KEY=' "$ROOT/.env" "$ROOT/keys.env" 2>/dev/null | tail -1 | cut -d= -f2- || true)"

if [[ -z "$alpaca_key" ]]; then
  alpaca_key="$(grep -E '^ALPACA_API_KEY=' "$ROOT/.env" 2>/dev/null | tail -1 | cut -d= -f2- || true)"
fi
if [[ -z "$alpaca_secret" ]]; then
  alpaca_secret="$(grep -E '^ALPACA_SECRET_KEY=' "$ROOT/.env" 2>/dev/null | tail -1 | cut -d= -f2- || true)"
fi

apex_url="${NEXT_PUBLIC_APEX_API_URL:-http://127.0.0.1:8000}"
market_url="${NEXT_PUBLIC_MARKETPLACE_API_URL:-http://127.0.0.1:8001}"

FRONTEND_ENV="$ROOT/autopilot-local/frontend/.env.local"

cat >"$OUT" <<EOF
# Generated by scripts/sync-copy-trading-env.sh — do not commit
NEXT_PUBLIC_APEX_API_URL=${apex_url}
NEXT_PUBLIC_MARKETPLACE_API_URL=${market_url}
NEXT_PUBLIC_API_URL=${apex_url}
ALPACA_API_KEY=${alpaca_key}
ALPACA_API_SECRET=${alpaca_secret}
ALPACA_BASE_URL=${alpaca_url:-https://paper-api.alpaca.markets}
ALPACA_DATA_URL=https://data.alpaca.markets
SEC_API_KEY=${sec_key}
QUIVER_API_KEY=${quiver_key}
PAPER_ALLOCATION_USD=100000
AUTOPILOT_DB_PATH=${ROOT}/autopilot-local/autopilot.db
EOF

cp -f "$OUT" "$FRONTEND_ENV" 2>/dev/null || true
echo "Wrote $OUT (and $FRONTEND_ENV)"
